### ISSUE TITLE
S9: As a user, I want the option to Match with the User that played the Card after I select that I like a Card

### ISSUE THREAD

**Issue by anhuwi** [sopra-fs22-group-07/server#10]
- [x] sopra-fs22-group-07/server#40
- [x] sopra-fs22-group-07/server#41 
- [x] sopra-fs22-group-07/server#57
- [x] sopra-fs22-group-07/client#26
