### ISSUE TITLE
S10: As a user I want to be able to chat with matched users to get to know them better.

### ISSUE THREAD

**Issue by anhuwi** [sopra-fs22-group-07/server#11]
- [x] sopra-fs22-group-07/client#95
- [x] sopra-fs22-group-07/server#136
- [x] sopra-fs22-group-07/server#137
- [x] #158
