### ISSUE TITLE
I1: Bugfixes

### ISSUE THREAD

**Issue by JoMuelle** [sopra-fs22-group-07/server#119]
- [x] sopra-fs22-group-07/client#91
- [x] sopra-fs22-group-07/client#92
- [x] sopra-fs22-group-07/server#122
- [x] sopra-fs22-group-07/client#90
- [x] sopra-fs22-group-07/client#89
- [x] sopra-fs22-group-07/client#88
- [x] sopra-fs22-group-07/client#126
- [x] #165
- [x] #194

**Comment by JoMuelle** [comment]
- [ ] unregistered Users or not logged in Users reach menu on Startup
- [ ] On logging in User has to pick a black Card even if user already has a black card
- [ ] Check Authorization Process
- [ ] Right Align Logout and profile button in header
- [ ] Remove Unnecessary Guards
- [ ] access to user, protection with userGuard: add check if token is in database (in the moment in the userGuard we only veryfy that there is something stored in "token" but not if this token exists in our database.)
