### ISSUE TITLE
S11: As a user I want to block or unmatch users to avoid unwanted conections with other users.

### ISSUE THREAD

**Issue by anhuwi** [sopra-fs22-group-07/server#12]
- [x] sopra-fs22-group-07/client#93
- [x] sopra-fs22-group-07/server#127
- [x] sopra-fs22-group-07/server#155
- [x] sopra-fs22-group-07/server#129
