### ISSUE TITLE
S14: As a user, I want to set a location-radius in which I only get cards from others users being in a radius near me

### ISSUE THREAD

**Issue by anhuwi** [sopra-fs22-group-07/server#149]
- [x] sopra-fs22-group-07/server#159 
- [x] sopra-fs22-group-07/server#175
- [x] sopra-fs22-group-07/server#176
- [x] sopra-fs22-group-07/client#156
