### ISSUE TITLE
S1: As a user I want to be able to either login with an existing account or register with a new one.

### ISSUE THREAD

**Issue by anhuwi** [sopra-fs22-group-07/server#2]
- [x] sopra-fs22-group-07/client#11
- [x] sopra-fs22-group-07/server#15
- [x] sopra-fs22-group-07/client#13
- [x] sopra-fs22-group-07/client#20
- [x] sopra-fs22-group-07/client#19
- [x] sopra-fs22-group-07/server#49
- [x] sopra-fs22-group-07/client#29
- [x] sopra-fs22-group-07/client#30
- [x] sopra-fs22-group-07/client#28
- [x] sopra-fs22-group-07/client#33
- [x] sopra-fs22-group-07/client#12
- [x] sopra-fs22-group-07/client#51
