### ISSUE TITLE
S2: As a user I want to be able to deactivate my account, because I might leave the game/app. My data gets deleted in the database and my account is not visible anymore for other players

### ISSUE THREAD

**Issue by anhuwi** [sopra-fs22-group-07/server#3]
first complete userstory 3
- [x] sopra-fs22-group-07/server#17
- [x] sopra-fs22-group-07/server#18
- [x] sopra-fs22-group-07/server#19
- [x] sopra-fs22-group-07/client#45
