### ISSUE TITLE
S3: As a user I want to be able to log into my account and there be able to view and change my personal data (e.g. email, address, etc.).

### ISSUE THREAD

**Issue by anhuwi** [sopra-fs22-group-07/server#4]
- [x] sopra-fs22-group-07/client#22
- [x] sopra-fs22-group-07/client#23
- [x] sopra-fs22-group-07/client#21
- [x] sopra-fs22-group-07/client#10
- [x] sopra-fs22-group-07/server#21
- [x] sopra-fs22-group-07/server#22
- [x] sopra-fs22-group-07/server#23
