### ISSUE TITLE
S5: As a user I want to have N white cards per Day (8 in hand, n in total per day), to fill in the blanks of other users black cards

### ISSUE THREAD

**Issue by anhuwi** [sopra-fs22-group-07/server#42]
- [x] sopra-fs22-group-07/server#28
- [x] sopra-fs22-group-07/server#29
- [x] sopra-fs22-group-07/client#17
- [x] sopra-fs22-group-07/server#31
- [x] sopra-fs22-group-07/server#32
- [x] sopra-fs22-group-07/client#16
- [x] sopra-fs22-group-07/client#14
- [x] #105
