### ISSUE TITLE
S7: As a user I want to choose which White cards (which got played for my black card) I like and dislike

### ISSUE THREAD

**Issue by anhuwi** [sopra-fs22-group-07/server#43]
- [x] sopra-fs22-group-07/client#8
- [x] sopra-fs22-group-07/client#7
- [ ] sopra-fs22-group-07/client#27
