### ISSUE TITLE
S6: As a User I want to be able to play a white Card to fill in the gap to the black card presented to me

### ISSUE THREAD

**Issue by anhuwi** [sopra-fs22-group-07/server#44]
- [x] sopra-fs22-group-07/client#6
- [x] sopra-fs22-group-07/client#15
- [x] sopra-fs22-group-07/client#9
- [x] sopra-fs22-group-07/client#42
- [x] #55
