### ISSUE TITLE
S4: As a user I want to be able to pick 1 Black Card out of K Black cards per day as a sentence with blanks for other users to fill in.

### ISSUE THREAD

**Issue by anhuwi** [sopra-fs22-group-07/server#45]
- [x] sopra-fs22-group-07/server#24
- [x] sopra-fs22-group-07/server#25
- [x] sopra-fs22-group-07/client#76
- [x] sopra-fs22-group-07/server#27
- [x] sopra-fs22-group-07/client#25
- [ ] sopra-fs22-group-07/client#24
