### ISSUE TITLE
S8: As a user I want to choose the traits I am interested, so that I can only match with people having these traits.

### ISSUE THREAD

**Issue by anhuwi** [sopra-fs22-group-07/server#9]
- [x] sopra-fs22-group-07/client#97
- [x] #157 
- [x] sopra-fs22-group-07/client#98
- [ ] #198
- [x] sopra-fs22-group-07/client#96
- [x] sopra-fs22-group-07/server#134
